### ISSUE TITLE
uncaught GLError: gl-shader

### ISSUE THREAD

**Issue by SmokingSlim** [Jam3/ios-video-test#3]
![image](https://cloud.githubusercontent.com/assets/2242039/13838032/d800df38-ebcd-11e5-83b7-a263d32c498d.png)

getting some error after installing everything with sudo npm install and running npm run start / npm run build

shader.bind() is undefined and the Uncaught GLError: gl-shader: Error compiling vertex shader of unknown name (see npm glsl-shader-name):
error is present.

Do you know why?

The Demo on your site runs without a problem, but when I try the build it fails.

Thank you.

/S

**Comment by mattdesl** [comment]
I've updated the dependencies and pushed them to master. Can you pull, `npm install`, and then run `npm start` again?

Cheers! :beers:

**Comment by SmokingSlim** [comment]
Hi Matt! Works excellent! Thank you so much!

Will deep dive into your code to try and figure out how it works :D Thanks again!

/S
